### ISSUE TITLE
typeshed branch installation

### ISSUE THREAD

**Issue by kshpytsya** [davidhalter/jedi#1319]
When `typeshed` branch is installed not in "develop mode", e.g. by doing `pip install git+https://github.com/davidhalter/jedi@typeshed` or `git install /path/to/jedi-typeshed`, the contents of `jedi/third_party/typeshed` does not get installed.
Adding it to `package_data` in `setup.py` seems to fix it, but apparently some manual coding is needed to be able to add the files recursively.

**Comment by davidhalter** [comment]
A `git submodule update --init` is currently needed. I have changed setup.py and MANIFEST.in though, so you should be able to use at least proper sdist/wheel packages in the future.

**Comment by kshpytsya** [comment]
```
$ git clone --branch typeshed --recurse-submodules https://github.com/davidhalter/jedi
Cloning into 'jedi'...
remote: Enumerating objects: 434, done.
remote: Counting objects: 100% (434/434), done.
remote: Compressing objects: 100% (176/176), done.
remote: Total 41251 (delta 273), reused 354 (delta 241), pack-reused 40817
Receiving objects: 100% (41251/41251), 10.05 MiB | 1.40 MiB/s, done.
Resolving deltas: 100% (31128/31128), done.
Submodule 'jedi/third_party/typeshed' (https://github.com/davidhalter/typeshed.git) registered for path 'jedi/third_party/typeshed'
Cloning into '/tmp/665/jedi/jedi/third_party/typeshed'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 20323 (delta 13), reused 22 (delta 12), pack-reused 20293
Receiving objects: 100% (20323/20323), 4.33 MiB | 1.21 MiB/s, done.
Resolving deltas: 100% (13801/13801), done.
error: Server does not allow request for unadvertised object 766ee7dd8cc7c8c9c28482abed58357124b75ee6
Fetched in submodule path 'jedi/third_party/typeshed', but it did not contain 766ee7dd8cc7c8c9c28482abed58357124b75ee6. Direct fetching of that commit failed.
```

**Comment by davidhalter** [comment]
hmm that's strange. Can you try again. I pushed the branch again (some commits might not have been included)?!

**Comment by kshpytsya** [comment]
Still the same. Tested on two machines in different locations.

**Comment by davidhalter** [comment]
Ok. I'm definitely stupid. I force pushed a branch on the typeshed fork. However that was after merging to master. Just don't use the typeshed branch anymore, use master:

```
git clone --recurse-submodules https://github.com/davidhalter/jedi
```
My bad. Sorry. Just deleted the branches to avoid further confusion.
