### ISSUE TITLE
Tab completion is broken in IPython

### ISSUE THREAD

**Issue by maxwellmckinnon** [davidhalter/jedi#1373]
ipython 7.6.1
jedi 0.14.0
python 3.7.3

```
In [1]: import numpy

In [2]: import IPython

In [3]: ipy = IPython.get_ipython()

In [4]: ipy.Completer.all_completions("numpy.")
Out[4]: []
```

On jedi 0.13.3, tab completion still doesn't work, but it claims it can generate the completions now.
```
ipy.Completer.all_completions("numpy.")
Out[4]:
['numpy.abs',
 'numpy.absolute',
 'numpy.absolute_import',
 'numpy.add',
 'numpy.add_docstring',
# ...
```

**Comment by davidhalter** [comment]
Proably related to #1370, fix coming soon.

**Comment by maxwellmckinnon** [comment]
Downgrading to 0.13.3, it actually does work, it's just very very slow. `pip uninstall jedi` works for now to get standard (non-awesome) autocompletion.

**Comment by maxwellmckinnon** [comment]
It is also a problem in Jupyter, no autocomplete there on 0.14.0.

This thread describing the issue on the IPython side claims using jedi + python repl works just fine, so it seems it's an IPython issue?

https://github.com/ipython/ipython/issues/11798

**Comment by davidhalter** [comment]
It seems to work for me, but maybe numpy is installed in a different way for you and the bug I quoted above is still the issue.

**Comment by bhodorog** [comment]
I'm sorry for confusing everyone with my post on ipython/ipython#11798 but  indeed the problem seems to be in jedi and it seems to be related to #1370 as correctly identified by @davidhalter.

The reason for my confusion was a virtualenv configuration error on my system, which caused python repl to use jedi==0.12, despite the fact that I was having activated a virtualenv with jedi==0.14.1. 

The steps to reproduce the problem is:
```
virtualenv --python python3 jedi-completion-bug
source jedi-completion-bug/bin/activate
pip install jedi
export PYTHONSTARTUP=$(python -m jedi repl)
python
>> import sys
>> sys.<tab>
```
The above sequence triggers an `AssertionError: <MixedObject: <module 'sys' (built-in)>>` at:
_jedi/evaluate/gradual/conversion.py", line 43, in _infer_from_stub_

I guess now we'll wait for the fix.

**Comment by davidhalter** [comment]
I just merged #1370, so this should be fixed. Wait for the next release or test it now. I will of course reopen if it's still an issue with the next release.

**Comment by minrk** [comment]
Just chiming in here from the IPython side to confirm that this issue is indeed fixed in master (3a9dc0ca2e2f9fd35b3a30a1cfb1653cb600bb4c)

**Comment by KOLANICH** [comment]
Just installed the latetst jedy (499408657bd350662a9a779d8bc6643b1acb6523) and ipython 
(1879ed27bb0ec3be5fee499ac177ad14a9ef7cfd). This issue isn't fixed.

`Python 3.7.3 (default, Mar 28 2019, 10:38:38) [MSC v.1915 32 bit (Intel)]`

**Comment by davidhalter** [comment]
Strange. Also `numpy.`? I doubt that it's not fixed, because for me it's working now, when it wasn't before this patch.

**Comment by KOLANICH** [comment]
>Also numpy.? 

Yes.

**Comment by KOLANICH** [comment]
> I doubt that it's not fixed, because for me it's working now, when it wasn't before this patch.

I have checked on an Ubuntu machine. It doesn't there too. I have also upgraded parso just to be sure that it is not because of it.

**Comment by davidhalter** [comment]
Are you sure that you are using the right Jedi version? Also if you actually want to help me debug this, could you just run it like this:

```
>>> import jedi, numpy, sys
>>> sys.version_info
sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
>>> jedi.__version__
'0.14.1'
>>> jedi.Interpreter('numpy.', [globals()]).completions()
[<Completion...]
```
? I want to see a traceback.

**Comment by KOLANICH** [comment]
<details>
<summary>log</summary>
```
In [1]: %paste
import jedi, numpy, sys
print(sys.version_info)
print(jedi.__version__)
interp = jedi.Interpreter('numpy.', [globals()])
print(interp.completions())
## -- End pasted text --
sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0)
0.14.1
---------------------------------------------------------------------------
AttributeError							Traceback (most recent call last)
%ANACONDA%\lib\site-packages\jedi\cache.py in wrapper(self)
	 45		 try:
---> 46			 return getattr(self, name)
	 47		 except AttributeError:

AttributeError: 'MixedName' object has no attribute '_infer'

During handling of the above exception, another exception occurred:

KeyError								  Traceback (most recent call last)
%ANACONDA%\lib\site-packages\jedi\evaluate\compiled\access.py in wrapper(evaluator, obj, parent_context)
	111			 try:
--> 112				 cache[key]
	113				 return cache[key][0]

KeyError: 82232112

During handling of the above exception, another exception occurred:

AssertionError							Traceback (most recent call last)
<ipython-input-1-9ccaf6e616c1> in <module>
	  3 print(jedi.__version__)
	  4 interp = jedi.Interpreter('numpy.', [globals()])
----> 5 print(interp.completions())

%ANACONDA%\lib\site-packages\jedi\api\__init__.py in completions(self)
	213				 self._pos, self.call_signatures
	214			 )
--> 215			 return completion.completions()
	216
	217	 def goto_definitions(self, **kwargs):

%ANACONDA%\lib\site-packages\jedi\api\completion.py in completions(self)
	115									self.stack, self._like_name)
	116
--> 117		 return sorted(completions, key=lambda x: (x.name.startswith('__'),
	118												   x.name.startswith('_'),
	119												   x.name.lower()))

%ANACONDA%\lib\site-packages\jedi\api\completion.py in filter_names(evaluator, completion_names, stack, like_name)
	 45				 len(like_name)
	 46			 )
---> 47			 k = (new.name, new.complete)  # key
	 48			 if k in comp_dct and settings.no_completion_duplicates:
	 49				 comp_dct[k]._same_name_completions.append(new)

%ANACONDA%\lib\site-packages\jedi\api\classes.py in complete(self)
	455
	456		 """
--> 457		 return self._complete(True)
	458
	459	 @property

%ANACONDA%\lib\site-packages\jedi\api\classes.py in _complete(self, like_name)
	424			 append = '('
	425
--> 426		 if self._name.api_type == 'param' and self._stack is not None:
	427			 nonterminals = [stack_node.nonterminal for stack_node in self._stack]
	428			 if 'trailer' in nonterminals and 'argument' not in nonterminals:

%ANACONDA%\lib\site-packages\jedi\evaluate\compiled\mixed.py in api_type(self)
	115	 @property
	116	 def api_type(self):
--> 117		 return next(iter(self.infer())).api_type
	118
	119

%ANACONDA%\lib\site-packages\jedi\cache.py in wrapper(self)
	 46			 return getattr(self, name)
	 47		 except AttributeError:
---> 48			 result = func(self)
	 49			 setattr(self, name, result)
	 50			 return result

%ANACONDA%\lib\site-packages\jedi\evaluate\compiled\mixed.py in infer(self)
	109				 if c is None or isinstance(c, MixedObject)
	110				 else ContextSet({create_cached_compiled_object(c.evaluator, access, c)})
--> 111				 for c in contexts
	112			 )
	113		 return contexts

%ANACONDA%\lib\site-packages\jedi\common\context.py in from_sets(cls, sets)
	 30		 """
	 31		 aggregated = set()
---> 32		 for set_ in sets:
	 33			 if isinstance(set_, BaseContextSet):
	 34				 aggregated |= set_._set

%ANACONDA%\lib\site-packages\jedi\evaluate\compiled\mixed.py in <genexpr>(.0)
	109				 if c is None or isinstance(c, MixedObject)
	110				 else ContextSet({create_cached_compiled_object(c.evaluator, access, c)})
--> 111				 for c in contexts
	112			 )
	113		 return contexts

%ANACONDA%\lib\site-packages\jedi\evaluate\compiled\access.py in wrapper(evaluator, obj, parent_context)
	115				 # TODO wuaaaarrghhhhhhhh
	116				 if attribute_name == 'mixed_cache':
--> 117					 result = func(evaluator, obj, parent_context)
	118				 else:
	119					 result = func(evaluator, obj)

%ANACONDA%\lib\site-packages\jedi\evaluate\compiled\mixed.py in _create(evaluator, access_handle, parent_context, *args)
	267				 evaluator.module_cache.add(string_names, ContextSet([module_context]))
	268		 else:
--> 269			 assert parent_context.tree_node.get_root_node() == module_node
	270			 module_context = parent_context.get_root_context()
	271

AssertionError:

In [2]:
```
</details>

**Comment by davidhalter** [comment]
Fixed something else that might be related to this. Can you retry? You need to do it with master.

**Comment by KOLANICH** [comment]
Now works, thank you!

**Comment by maxwellmckinnon** [comment]
Confirmed working in jedi 0.15.1. ipython 7.7.0 python 3.7.4
Thanks so much!

**Comment by maxwellmckinnon** [comment]
This is broken again in 
```
jedi==0.15.1
ipython==7.8.0
Python 3.7.4
```

Was this not fixed with an added unit test against this? :P

```
In [1]: import numpy as np
i
In [2]: import IPython

In [3]: ipy = IPython.get_ipython()

In [4]: ipy.Completer.all_completions("numpy.")
Out[4]: []
```

**Comment by davidhalter** [comment]
@maxwellmckinnon Please open a new issue.

**Comment by ArrowRaider** [comment]
Stock download+install of Anaconda3 has broken autocomplete in Jupyter.  Do I report the issue here since autocomplete works if I run this:
%config IPCompleter.use_jedi = False

**Comment by davidhalter** [comment]
Not really. It might have to do something with the versions. If it worked before, anaconda3 might you a different version than jupyter. It might be worth isolating that stuff with virtualenvs.

**Comment by LeninGF** [comment]
I run into this problem. It seems that the problem is with the parse file. In fact, I applied conda update --all -c conda-forge. This seems to have fixed the problem by changing the version of parso; which was downgraded

parso                                          0.8.0-py_0 --> 0.5.2-py_0

So. I acknowledge that the problem exist and it was activated when I updated conda version  to latest 4.8.4. Update caused the problem

**Comment by davidhalter** [comment]
See also https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/issues/81#event-3664361521 (It's a conda bug).

**Comment by LeninGF** [comment]
Thanks for sharing your knowledge
Atentamente,

Lenin Falconí Estrada

**Comment by arjunsohanlal** [comment]
Just came over to this thread with the same issue, and I'd noticed that an old conda install seemed to have the right package versions that allowed for stable tab-autocomplete. Here are the versions that seem to work for me right now (running Python 3.8.7):
```
backcall==0.1.0
Click==7.0
colorama==0.4.3
decorator==4.4.1
ipython==7.12.0
ipython-genutils==0.2.0
itsdangerous==1.1.0
jedi==0.14.0
Jinja2==2.11.1
MarkupSafe==1.1.1
parso==0.5.2
pickleshare==0.7.5
prompt-toolkit==3.0.3
Pygments==2.5.2
six==1.14.0
traitlets==4.3.3
wcwidth==0.1.8
Werkzeug==1.0.0
```
I'm afraid that I haven't been able to narrow down further into **which exact packages** were the troublemakers, but I hope this works out for you.

**Comment by davidhalter** [comment]
Remember to always read closed issues: https://github.com/davidhalter/jedi/issues/1714
