### ISSUE TITLE
Type hint for __getitem__ does not work

### ISSUE THREAD

**Issue by kgr3** [davidhalter/jedi#1719]
Jedi 0.18.0
Python 3.8.1
Windows 10

I'm trying to provide a type hint for `__getitem__` to make jedi auto-completion work.
My (stupid) test case:

```
class Base:
  def foo(self):
    return 42

class C:
  def __init__(self):
    self.child = Base()
  def __getitem__(self,key) -> Base:
    return self.child

c=C()
c[0].<TAB>
```

Upon pressing TAB, I was expecting to see `foo`. Instead, nothing is shown (`Base().<TAB>` correctly displays `foo`).
Is this a supported scenario?

**Comment by davidhalter** [comment]
I guess you are talking about Interpreter completions in IPython?

**Comment by kgr3** [comment]
No, I'm testing with `jedi repl` using cpython and pyreadline. The ultimate goal is to integrate Jedi into my own project, but I need to have working `__getitem__` completion for that. I very much prefer Jedi's simplicity over the LSP approach. 

FWIW,  <https://github.com/microsoft/vscode-python/issues/2446#issuecomment-428781959> mentions a similar-looking problem.

**Comment by davidhalter** [comment]
For `Script` (which is what VSCode is using), `__getitem__` works.

**Comment by kgr3** [comment]
I did some testing, and indeed `Script` appears to work correctly with `__getitem__`. Nice!

It looks like `jedi repl` is using `Interpreter` though, and that fails to complete `__getitem__`.  To rule out possible pyreadline issues, I repeated the test also on Ubuntu 18.04 (WSL), and it has the same behavior.

My project has a custom REPL interface, and I'm unsure on how practical it would be to use `Script` instead of `Interpreter` there. Any advice/opinion on this?

Of course, ultimately it would be very nice to get `Interpreter` and `Script` provide equal feature set.

**Comment by kgr3** [comment]
I decided to go with the `Script` approach, keeping track of the REPL session and feeding that into `Script`  upon every key event. I'm hoping `jedi` caching will keep the response time tolerable.

Many thanks for your help. Happy holidays!

**Comment by davidhalter** [comment]
This should work now, fixed in 971913be3597543ea2e830ce1cc0839423666b7b

I also made `__iter__` work and checked that `__next__` works properly.

**Comment by kgr3** [comment]
Eager to try out this fix, I installed latest jedi with

  pip install -e git://github.com/davidhalter/jedi.git#egg=jedi

However, __getitem__ completion still does not work as expected:

```
>>> import jedi
>>> class GetItemCls:
...    def __getitem__(self,key) -> int:
...      pass
...
>>> jedi.Interpreter('GetitemCls()[0]', [locals()]).infer()
[]
```

**Comment by davidhalter** [comment]
There's a typo in your example ;)

**Comment by kgr3** [comment]
You're right. How embarrassing :-)! In my defense I only tried this after my own class failed. Digging deeper, it seems variable type inference for some reason fails:

```
>>> import jedi
>>> class GetItemCls:
...   def __getitem__(self,key) -> int:
...     pass
...
>>> jedi.Interpreter('GetItemCls()[0]', [locals()]).infer()
[<Name full_name='builtins.int', description='instance int'>]
>>> x=GetItemCls()
>>> jedi.Interpreter('x[0]', [locals()]).infer()
[]
>>> locals()['x']
<__main__.GetItemCls object at 0x000001CABB4EF340>
```
So jedi does not infer the correct type for `x` above it seems?

**Comment by davidhalter** [comment]
Good point. Even though it looks like the same thing, it's entirely different code that handles that. But it should be fixed now.

**Comment by kgr3** [comment]
Thanks for the quick response. Indeed, the above example works as expected now.

However, I'm still having trouble with my custom classes located in module `dicom`:

```
>>> import jedi
>>> import dicom
>>> x=dicom.Iod(r"c:\iod\rp.dcm")
>>> y=x.root.BeamSequence
>>> jedi.Interpreter('y',[locals()]).infer()
[<Name full_name='dicom.Sequence', description='instance Sequence'>]
>>> jedi.Interpreter('y[0]',[locals()]).infer()
[]
>>> jedi.Interpreter('y[0]:dicom.Sequence',[locals()]).infer()
[<Name full_name='dicom.Sequence', description='class pybind11_type'>]
>>> y[0]
Sequence((fffe,e000)    1 Beam Sequence [0])
```

As you can see, jedi correctly infers type for `y`, but fails for `y[0]` unless explicitly typed.
I haven't been yet able to find out the reason, will continue digging.
(I don't know if this is relevant, but module `dicom` has been implemented in C++ with pybind11.  I wonder if I should be supplying .pyi files for these. OTOH jedi seems to have no trouble inferring `y` above.)

**Comment by kgr3** [comment]
Update: I ran stubgen, and partial output for `dicom.Sequence` is
```
    @overload
    def __getitem__(self, arg0: int) -> Sequence: ...
    @property
    def BeamSequence(self) -> dicom.Sequence: ...
    @BeamSequence.setter
    def BeamSequence(self, val: dicom.Sequence) -> None: ...
```
There are several overloads for `__getitem__`. Could this be the problem?

**Comment by davidhalter** [comment]
Sorry I have no idea what `dicom.Sequence` is. In general there's still an issue with resolving stuff like `Sequence[int]`, because the runtime does not give me any help. It's essentially just an object that Jedi has a hard time to deal with. This could of course be improved but is quite hard to do.

What usually helps a lot is when Jedi can identify the code by using `__file__`. At that point static analysis can be used to help you. This is what happens with a lot of people's libraries. That's also why I'm not really interested in fixing the `Sequence[int]` case I described above: It does not help most users unless they are writing extensions or use a very weird import system.
