### ISSUE TITLE
Jedi not correctly caching since v0.10.0?

### ISSUE THREAD

**Issue by leifdenby** [davidhalter/jedi#972]
I've been digging through jedi's source to try and find out why completions in `jedi-vim` appeared to have slowed down a lot. I think this is related to https://github.com/davidhalter/jedi/issues/915, but I just wanted to add this in case it's useful. I used the following small example of getting completions for `matplotlib`

`comp.py`:
```
# coding: utf-8
import time
import jedi

source = """
import matplotlib
matplotlib."""
script = jedi.Script(source, 3, len("matplotlib."))

start = time.time()
script.completions()
end = time.time()
print(end - start)

start = time.time()
script.completions()
end = time.time()
print(end - start)
```

And checked the execution time with different versions of `jedi`:

```
~ » pip install --force jedi==0.11.0                                                                                                                                                        leifdenby@aiode
Collecting jedi==0.11.0
  Using cached jedi-0.11.0-py2.py3-none-any.whl
Requirement already satisfied: parso==0.1.0 in /usr/local/lib/python2.7/site-packages (from jedi==0.11.0)
Installing collected packages: jedi
  Found existing installation: jedi 0.9.0
    Uninstalling jedi-0.9.0:
      Successfully uninstalled jedi-0.9.0
Successfully installed jedi-0.11.0
------------------------------------------------------------
~ » python2 comp.py                                                                                                                                                                         leifdenby@aiode
2.47454810143
0.0182299613953
------------------------------------------------------------
~ » python2 comp.py                                                                                                                                                                         leifdenby@aiode
2.45317602158
0.0187478065491
------------------------------------------------------------
~ » pip install --force jedi==0.10.0                                                                                                                                                        leifdenby@aiode
Collecting jedi==0.10.0
  Using cached jedi-0.10.0-py2.py3-none-any.whl
Installing collected packages: jedi
  Found existing installation: jedi 0.11.0
    Uninstalling jedi-0.11.0:
      Successfully uninstalled jedi-0.11.0
Successfully installed jedi-0.10.0
------------------------------------------------------------
~ » python2 comp.py                                                                                                                                                                         leifdenby@aiode
3.70782780647
0.0290880203247
------------------------------------------------------------
~ » python2 comp.py                                                                                                                                                                         leifdenby@aiode
1.58455777168
0.0244128704071
------------------------------------------------------------
~ » pip install --force jedi==0.9.0                                                                                                                                                         leifdenby@aiode
Collecting jedi==0.9.0
  Using cached jedi-0.9.0-py2.py3-none-any.whl
Installing collected packages: jedi
  Found existing installation: jedi 0.10.0
    Uninstalling jedi-0.10.0:
      Successfully uninstalled jedi-0.10.0
Successfully installed jedi-0.9.0
------------------------------------------------------------
~ » python2 comp.py                                                                                                                                                                         leifdenby@aiode
0.525048017502
0.022253036499
------------------------------------------------------------
~ » python2 comp.py                                                                                                                                                                         leifdenby@aiode
0.0883800983429
0.0226149559021
```

It looks like `v0.10.0` and `v0.11.0` are significantly slower than `v0.9.0`, but `v0.11.0` is definitely faster than `v0.10.0`. What is more curious is that in the second call to `v0.11.0` the execution is almost the same as the first time round, whereas for the other versions they are significantly faster in the second call. This suggests to me that in `v0.11.0` the caching isn't quite working.

Hope this is useful. I was going to look into `parso` to understand how the caching works, but I will wait with that. For now I will revert to using `v0.9.0`.

Thanks for an fantastic tool though! I use this code literally every day.

**Comment by davidhalter** [comment]
Can you please look at the 4 latest pull requests that I merged in parso? I think there a lot of those issues were fixed?! Thank you for the report!

**Comment by leifdenby** [comment]
Yup, I'll give that a try and let you know.

**Comment by leifdenby** [comment]
I've just run the test above against  too and gotten:

```
Collecting git+git://github.com/davidhalter/jedi.git@v0.9.0
  Cloning git://github.com/davidhalter/jedi.git (to v0.9.0) to /private/var/folders/jn/5t2vrk0s6d32bbq3ys3y4j1w0000gn/T/pip-2CdAgw-build
Installing collected packages: jedi
  Running setup.py install for jedi ... done
Successfully installed jedi-0.9.0
First call:
0.602230072021
0.0285210609436
Second call:
0.100098133087
0.0234580039978
Collecting git+git://github.com/davidhalter/jedi.git@v0.10.0
  Cloning git://github.com/davidhalter/jedi.git (to v0.10.0) to /private/var/folders/jn/5t2vrk0s6d32bbq3ys3y4j1w0000gn/T/pip-mdbZvX-build
Installing collected packages: jedi
  Running setup.py install for jedi ... done
Successfully installed jedi-0.10.0
First call:
3.74930000305
0.0249230861664
Second call:
1.5718998909
0.0232748985291
Collecting git+git://github.com/davidhalter/jedi.git@v0.11.0
  Cloning git://github.com/davidhalter/jedi.git (to v0.11.0) to /private/var/folders/jn/5t2vrk0s6d32bbq3ys3y4j1w0000gn/T/pip-NroRzl-build
Collecting parso==0.1.0 (from jedi==0.11.0)
  Using cached parso-0.1.0-py2.py3-none-any.whl
Installing collected packages: parso, jedi
  Running setup.py install for jedi ... done
Successfully installed jedi-0.11.0 parso-0.1.0
First call:
1.78660798073
0.0180079936981
Second call:
1.75186610222
0.0184109210968
Collecting git+git://github.com/davidhalter/parso.git@5b5d855fabe82ffce3ae564267afb01d8b37ef02
  Cloning git://github.com/davidhalter/parso.git (to 5b5d855fabe82ffce3ae564267afb01d8b37ef02) to /private/var/folders/jn/5t2vrk0s6d32bbq3ys3y4j1w0000gn/T/pip-3PQtQJ-build
  Could not find a tag or branch '5b5d855fabe82ffce3ae564267afb01d8b37ef02', assuming commit.
Installing collected packages: parso
  Running setup.py install for parso ... done
Successfully installed parso-0.1.0
Collecting git+git://github.com/davidhalter/jedi.git@v0.11.0
  Cloning git://github.com/davidhalter/jedi.git (to v0.11.0) to /private/var/folders/jn/5t2vrk0s6d32bbq3ys3y4j1w0000gn/T/pip-TWEBiB-build
Installing collected packages: jedi
  Running setup.py install for jedi ... done
Successfully installed jedi-0.11.0
First call:
0.744444847107
0.01828789711
Second call:
0.744567155838
0.0196011066437
```

It's definitely faster with that version of `parso`, but still doesn't appear to be caching correctly (since the second call takes as long as the first one).

I've put together a quick repo for the code I'm doing these test with and put it on github https://github.com/leifdenby/jedi-testing so you can have a try at running these yourself. I've linked it up with travis too so it'll automatically be rerun on pull-requests. Although travis is significantly faster than my machine (!) the same issue appears there.

**Comment by kogelnik** [comment]
I see this problem as well.  (Modern machine, OS X, SSD.)

It's definitely an issue with larger libraries.  For example v0.11 versus parso master using the above method:


                      v0.11                  parso master
                    ------------------     -----------------
     module         1st call   2nd call    1st call   2nd call
     tensorflow      19.8s       0.3s         15.8s     0.2s
     sympy           19.5s       0.5s         15.3s     0.2s
     scipy           16.8s       0.2s         13.6s     0.2s
     matplotlib       2.6s       0.0s          1.8s     0.0s

The first call is always hit with the delay.  For example, running the test again, the results are identical, and not improved as would be expected from hitting a cache.  It's as if the disk cache is not being utilized.

Inside vim with only jedi-vim enabled the situation is worse. The initial command completion takes many times longer.  For tensorflow it was about a minute (hand-timed), which makes it very frustrating to use.

Loading the pickled cache file sizes for the libraries I have installed range from a few hundred bytes to 2.6MB, and the load times were typically under 1ms, with a few being around 20ms, and in a couple of instances around 0.5s, so this is likely not to be the issue.

Currently on parso master, there is a disconnect between parso and jedi on where the cache directory is.  After setting jedi/settings.py cache_directory to be the same as parso, the cache was read, but this didn't help the time.  

Thanks.

**Comment by davidhalter** [comment]
I have just merged something in parso that might make it a lot better. Please retry. I'll try to release this weekend.

**Comment by kogelnik** [comment]
Huge performance increase!  Awesome David, well done!

                  no      cache   cache
                  cache   load    hit  
                  ---------------------  
    tensorflow    8.0s    2.2s    0.2s
    scipy         6.8s    2.1s    0.2s
    sympy         7.4s    1.7s    0.2s
    matplotlib    1.0s    0.2s    0.0s 
   

Most libraries are now evaluated sub 0.1s.

Thanks for your work!  I'm sure this will make a big difference for a lot of people.

**Comment by davidhalter** [comment]
I'll close then. Glad you like it :)

I'll try to do a new jedi release very soon.

**Comment by kogelnik** [comment]
I'm curious: jedi-vim doesn't seem to pick up the installed jedi and parso, but has a copy in jedi-vim/pythonx.  Guessing this is done for stability.  However, the jedi-vim.txt mentions jedi must be installed.  Perhaps this needs to be updated?

Copying the new versions into jedi-vim got the performance improvement.  I might have missed something, but the initial completion speed still seems to be that of no-cache, rather than cache-load.

Thanks again!

**Comment by davidhalter** [comment]
It's a submodule in jedi-vim. It's mostly there for people that don't run pip on their computers and just want to install submodules. IMO it's still better to actually use `pip install jedi` - which you can easily do if you don't clone the submodules.

**Comment by kogelnik** [comment]
Installed jedi with pip, but jedi-vim with Vundle, which pulled in the submodules.

**Comment by leifdenby** [comment]
@davidhalter it's looking good! Much faster now (using most recent commits on master for both parso and jedi):

```
Collecting git+git://github.com/davidhalter/parso.git@0dea94c801a7e135dccb3911a59b8c942641f7ad
  Cloning git://github.com/davidhalter/parso.git (to 0dea94c801a7e135dccb3911a59b8c942641f7ad) to /private/var/folders/jn/5t2vrk0s6d32bbq3ys3y4j1w0000gn/T/pip-CzvnAw-build
  Could not find a tag or branch '0dea94c801a7e135dccb3911a59b8c942641f7ad', assuming commit.
Installing collected packages: parso
  Running setup.py install for parso ... done
Successfully installed parso-0.1.2
Collecting git+git://github.com/davidhalter/jedi.git@6ee361864c6ddb26a2f229b0f69fb0fb14acc6b6
  Cloning git://github.com/davidhalter/jedi.git (to 6ee361864c6ddb26a2f229b0f69fb0fb14acc6b6) to /private/var/folders/jn/5t2vrk0s6d32bbq3ys3y4j1w0000gn/T/pip-6p5N0T-build
  Could not find a tag or branch '6ee361864c6ddb26a2f229b0f69fb0fb14acc6b6', assuming commit.
Installing collected packages: jedi
  Running setup.py install for jedi ... done
Successfully installed jedi-0.11.1
First call:
0.292360067368
0.0190560817719
Second call:
0.284375190735
0.0186378955841
```

I'm still surprised that the second time jedi is called the call time isn't significantly smaller (0.29s ~ 0.28s) since it should just be loading the pickled information about the module being completed instead of parsing the module, right? Might it be worth loading all the pickled completion information into memory when parso is imported? (apologies if you're already doing this)

**Comment by davidhalter** [comment]
That is strange. On my computer it looks like this:

```
First:
2.06751704216
0.0156090259552
Second:
0.499650001526
0.0198669433594
```

I have an SSD and Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz.
Second try (after deleting the cache) looked similar.

Maybe you have an older version of parso installed still and it uses that somehow. No idea why it's not working for you.

**Comment by kogelnik** [comment]
I think it's working correctly.

There are 3 timing cases:
   1. no disk cache - the library needs to be read, parsed and written to cache (slow)
   2. unloaded disk cache - the picked parsing needs to to be read and loaded (faster)
   3. hit in loaded cache - everything is in memory (fastest)

@leifdenby, your numbers don't make sense as there should be 3 different times.  Delete your parso disk cache to get the effect.

For example,  loading tensorflow and the caches deleted:
      
     First run:
       12.75  - build the disk cache
        0.37  - memory cache hit
     Second run:
        2.44  - load disk cache
        0.37  - memory cache hit

There is still a substantial slowdown when running jedi-vim versus jedi in python, but the new version is much faster.

**Comment by davidhalter** [comment]
What do you mean by a substantial slowdown @kogelnik? I don't understand why jedi-vim should be any different than jedi.

**Comment by kogelnik** [comment]
The difference between the Python-based and vim code completion for is substantial for large libraries.  I don't know why, but here are the timings.

For tensorflow:

            no      cache  cache
            cache   load   hit
            ------------------
      vim     43    11      2
      python  13     2.6    0.4

The vim results are hand timed from entering the "." for code completion.

Large libraries amplify the difference, but it is there for any library.
 
One thing to note, the caches are re-written by jedi-vim even after jedi python has just been run (loading only the single library) -- a lot of new caches and more of them.

Hope this helps.

**Comment by kogelnik** [comment]
Seems like the cache names are not matching between jedi and jedi-vim.

For tensorflow, jedi is creating 55 files, while jedi-vim is creating 180 different files.

**Comment by davidhalter** [comment]
Hmmm, I'm pretty sure something is different in the vim Python version or you use a submodule there (and jedi/parso are in there as a submodule (it's not fixed there yet). After opening a Python file you can check where Jedi is used from here: `:PythonJedi print(jedi_vim.jedi)`.

The reason why jedi-vim is definitely not the problem is that the wrapper around completion does nothing - no caching - nothing. Maybe it has to do with loading docstrings and the like, but I doubt that (some of jedi's API is running lazily).

**Comment by kogelnik** [comment]
I had removed the pythonx submodules and *.pyc to get the improvements, and verified the Jedi path in vim points to the python jedi version.

For kicks, removing jedi-vim and reinstalling through Vundle, so the Jedi path is now the local jedi/parso pythonx submodule without the fix, yields 87s versus the fixed 43s for no disk cache.  Compare this to the python only result of 13s.

With both vim and python are pointing at the same module, why would jedi-vim and jedi python create different cache files?  Shouldn't they be the same?
And why would jedi-vim create many more files, 180 vs. 55 (for tensorflow)?

Using numpy:
no cache:  vim: 15s, 78 cache files created   
no cache:  python: 5s, 31 cache files created

Using os:
no cache: vim: 7 cache files created
no cache: python: 1 cache file created

Perhaps it's my environment, but something doesn't seem right.

Thanks.

**Comment by davidhalter** [comment]
Yeah something does indeed not seem right. jedi-vim definitely does not do anything with caches. That's entirely jedi/parso. 

I have no idea why this is happening. The only thing I would suspect is accessing `Completion().type` within jedi-vim (that's lazy and might use imports).

**Comment by yangle** [comment]
Is there any particular reason that the jedi + parso submodules in jedi-vim are not yet updated?
